### ISSUE TITLE
About your MSc Dissertation ？

### ISSUE THREAD

**Issue by CHNtao** [victorjo97/MNIST_memristor#1]
hey bro, I searched the relevant memristor cross array on GitHub and found your folder, but I didn't find your MSc dissertation on Google. Could you give a url link or upload files? I would greatly appreciate it if you would forward the necessary materials and relevant information at your convenience.

**Comment by victorjo97** [comment]
Hi CHNtao! Happy to share it with you. You can find it here: https://sites.google.com/view/vzamora/assignments in the first entry. Also happy to clarify any point.

**Comment by CHNtao** [comment]
Victorjo, thank you for your reply, but I encountered some problems when visiting the website. I can't access the contents of the file. Is it convenient for you to send a PDF file to my email. email: c878036049@hotmail.com

**Comment by victorjo97** [comment]
Hi, sorry for the inconvenience. I wasn't aware that the proper permissions were activated. Now you should be able to enter it at https://sites.google.com/view/vzamora/assignments

**Comment by CHNtao** [comment]
Thank you for your patience in solving my problem. Now I can access the content about your MSc Dissertation.

发自我的iPhone
